# Generated by Django 4.2.4 on 2025-04-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=100)),
                ('seasons', models.DateField()),
            ],
        ),
    ]
