# Generated by Django 4.1.13 on 2025-04-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
