# Generated by Django 4.2.4 on 2025-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_shows_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home_page_images/')),
            ],
        ),
    ]
