# Generated by Django 4.1.13 on 2025-04-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_home_page'),
        ('api', '0006_payment'),
    ]

    operations = [
    ]
