# Generated by Django 4.1.13 on 2025-04-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
