# Generated by Django 5.2 on 2025-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ticket_qr_code_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
