# Generated by Django 5.2 on 2025-04-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_movies_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='VALID', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='api.order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_path',
            field=models.CharField(max_length=255),
        ),
    ]
